version: '2.1'

services:
    db:
      image: postgres:10.5
      restart: always
      environment: 
        POSTGRES_USER: root
        POSTGRES_PASSWORD: tiger
        POSTGRES_DB: phoenix
    ports: 
      - 5440:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
    api:
      build: .
      depends_on: 
        - db
      environment:
        SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://root:tiger@db/phoenix
      ports:
        - "8080:8080"
      volumes: 
        - .:/app
      restart: always